Repository athensresearch/athens, pull requests merged in 2021-02, with the labels that each got.

#608 Add loom links to README.md
  README.md
Labels: t/docs

#593 Outdated welcome page
  src/cljs/athens/athens_datoms.cljs
Labels: t/docs

#628 fix: windows sentry variable
  .github/workflows/build.yml
Labels: f/telemetry, os/windows

#578 fix(keybindings): partial solution to #573
  src/cljs/athens/keybindings.cljs
Labels: d/medium, f/keybindings

#648 New icon and capitalized title
  build/icon.png
  package-lock.json
  package.json
Labels: design, logo

#645 feat(graph-viz): first pass
  package.json
  src/cljs/athens/router.cljs
  src/cljs/athens/views.cljs
  src/cljs/athens/views/app_toolbar.cljs
  src/cljs/athens/views/graph_page.cljs
  yarn.lock
Labels: f/graph-viz, t/feature

#654 enhance(analytics): track opt-in/opt-out
  src/cljs/athens/views/settings_page.cljs
Labels: f/telemetry

#655 feat(web-app): create a web version that doesn't persist
  .github/workflows/build.yml
  project.clj
  resources/public/favicon.png
  resources/public/index.html
  shadow-cljs.edn
  src/cljs/athens/core.cljs
  src/cljs/athens/db.cljs
  src/cljs/athens/electron.cljs
  src/cljs/athens/events.cljs
  src/cljs/athens/util.cljs
  src/cljs/athens/views.cljs
  src/cljs/athens/views/app_toolbar.cljs
  src/cljs/athens/views/blocks.cljs
  src/cljs/athens/views/left_sidebar.cljs
  src/cljs/athens/ws.cljs
  src/js/textarea.js
Labels: t/electron, t/web

#660 fix: block title is not parsed
  src/cljs/athens/views/block_page.cljs
  src/cljs/athens/views/node_page.cljs
  src/cljs/athens/views/right_sidebar.cljs
Labels: f/block-page

#697 perf(graph-viz): replace react-force-graph w/ react-force-graph-2d
  package.json
  src/cljs/athens/views/graph_page.cljs
  yarn.lock
Labels: f/graph-viz, t/performance

#704 perf: use shadow-cljs release, improve job dependencies
  .github/workflows/build.yml
  package-lock.json
  package.json
Labels: gh-actions, shadow-cljs, t/chore, t/performance
