Repository athensresearch/athens, pull requests merged in 2021-09, with the labels that each got.

#1614 Fix: RTC timeout in docker-compose setup
  nginx.conf
Labels: t/bug, r/rtc

#1628 Feature: docker capture hprof when OOME
  Dockerfile
  docker-compose.yml
  script/docker-run-lan-party.sh
Labels: r/rtc

#1639 Fix: remote client freeze on navigate down
  src/cljs/athens/db.cljs
  src/cljs/athens/events.cljs
Labels: t/bug, r/rtc

#1642 Fix: escape hatch when connecting to remote
  src/cljs/athens/events/remote.cljs
  src/cljs/athens/self_hosted/client.cljs
Labels: r/rtc

#1617 fix: broadcast username on update
  src/clj/athens/self_hosted/web/presence.clj
  src/cljc/athens/common_events.cljc
  src/cljc/athens/common_events/schema.cljc
  src/cljs/athens/self_hosted/client.cljs
  src/cljs/athens/self_hosted/presence/events.cljs
  src/cljs/athens/self_hosted/presence/fx.cljs
  src/cljs/athens/views/pages/settings.cljs
Labels: r/rtc, t/presence

#1647 Fix: don't send TX data in db dump
  CHANGELOG.md
  package.json
  src/clj/athens/self_hosted/web/presence.clj
Labels: t/bug, r/rtc

#1651 Fix: concurrent resolution should not happen.
  src/clj/athens/self_hosted/web/datascript.clj
Labels: r/rtc

#1567 Feature: Drafting ADR for Atomic/Composite Graph Operations.
  doc/adr/0007-lan-party-datascript-events.md
  doc/adr/0010-atomic-composite-grapth-operations.md
  src/clj/athens/self_hosted/components/web.clj
  src/clj/athens/self_hosted/web/datascript.clj
  src/cljc/athens/common/utils.cljc
  src/cljc/athens/common_events.cljc
  src/cljc/athens/common_events/graph/atomic.cljc
  src/cljc/athens/common_events/graph/composite.cljc
  src/cljc/athens/common_events/graph/schema.cljc
  src/cljc/athens/common_events/resolver.cljc
  src/cljc/athens/common_events/resolver/atomic.cljc
  src/cljc/athens/common_events/schema.cljc
  src/cljs/athens/electron/images.cljs
  src/cljs/athens/events.cljs
  src/cljs/athens/events/remote.cljs
  src/cljs/athens/self_hosted/client.cljs
  src/cljs/athens/util.cljs
  src/cljs/athens/views/athena.cljs
  src/cljs/athens/views/blocks/textarea_keydown.cljs
  src/cljs/athens/views/pages/node_page.cljs
  test/athens/common_events/atomic_ops_test.clj
  test/athens/common_events/stress_test.clj
Labels: r/rtc

#1655 Fix: Sort linked references by date descending.
  src/cljs/athens/db.cljs
Labels: t/bug, f/linked-refs

#1656 Fix: Just errors and crashes sent to Sentry.
  package.json
  src/cljs/athens/core.cljs
  yarn.lock
Labels: t/bug

#1660 Atomic block split
  CHANGELOG.md
  package.json
  src/cljc/athens/common_events/graph/atomic.cljc
  src/cljc/athens/common_events/graph/ops.cljc
  src/cljc/athens/common_events/resolver/atomic.cljc
  src/cljs/athens/events.cljs
  src/cljs/athens/events/remote.cljs
  test/athens/common_events/atomic_ops/block_new_test.clj
  test/athens/common_events/atomic_ops/block_save_test.clj
  test/athens/common_events/atomic_ops/block_split_test.clj
  test/athens/common_events/atomic_ops/page_new_test.clj
Labels: r/rtc

#1668 fix: selection issues.
  src/cljs/athens/events.cljs
  src/cljs/athens/views/blocks/content.cljs
Labels: r/rtc, f/selection

#1650 Feature: Password protection for server.
  README.self-hosted.md
  src/clj/athens/self_hosted/clients.clj
  src/clj/athens/self_hosted/components/web.clj
  src/clj/athens/self_hosted/web/presence.clj
  src/clj/config.edn
  src/cljc/athens/common_events.cljc
  src/cljc/athens/common_events/schema.cljc
  src/cljs/athens/electron/db_modal.cljs
  src/cljs/athens/electron/utils.cljs
  src/cljs/athens/self_hosted/client.cljs
  src/cljs/athens/subs.cljs
Labels: r/rtc, f/security

#1645 fix: all pages is slow when a page has 100+ blocks
  src/cljc/athens/common_db.cljc
  src/cljs/athens/views/pages/all_pages.cljs
Labels: t/performance

#1685 Feature: block ordering
  src/clj/athens/self_hosted/web/datascript.clj
  src/cljc/athens/common_db.cljc
  src/cljc/athens/common_events/graph/schema.cljc
  src/cljc/athens/common_events/resolver/atomic.cljc
  src/cljs/athens/effects.cljs
  test/athens/common_events/orderkeeper_test.clj
Labels: r/rtc

#1688 chore: RTC Alpha 10
  CHANGELOG.md
  package.json
Labels: r/rtc

#1692 fix: less logs, more testing
  src/cljc/athens/parser/impl.cljc
  test/athens/common_events/orderkeeper_test.clj
Labels: r/rtc
